# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/openMicNight/

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies
          command: |
            cd openMicNight && poetry install
      - run:
          name: Analysis
          command: |
            cd openMicNight && make analysis
      - run:
          name: Tests
          command: |
            cd openMicNight && make test

  build_cpp:
    docker:
      - image: "scorpion454r/omncpp:latest"
    steps:
      - run: Export test results.

workflows:
  version: 2
  build_cpp_app:
    jobs:
      - build:
          filters:
            branches:
              only: pyApp
      - build_cpp:
          filters:
            branches:
              only: cppAddition
