# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/openMicNight/

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies
          command: |
            cd openMicNight && poetry install
      - run:
          name: Analysis
          command: |
            cd openMicNight && make analysis
      - run:
          name: Tests
          command: |
            cd openMicNight && make test

  build_cpp:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run: ls -al
      - run
          name: Installing Sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get install -y cmake'
      - run:
          name: Install GTest
          command: 'sudo apt-get install -y libgtest-dev'
      - run:
          name: Build GTest
          command: 'cd cppOpenMicNight && ./install_gtest.sh'
      - run:
          name: Build Makefile
          command: 'cd cppOpenMicNight && cmake CMakeLists.txt'
      - run:
          name: Build Src
          command: 'cd cppOpenMicNight && make'
      - run:
          name: Run Tests
          command: 'cd cppOpenMicNight && ./allTests'

workflows:
  version: 2
  build_cpp_app:
    jobs:
      - build:
          filters:
            branches:
              only: pyApp
      - build_cpp:
          filters:
            branches:
              only: cppAddition
